name: yaroorm
description: Easy migrations, query-builder & ORM for Postgres, SQLite, MySQL & MariaDB.
version: 0.0.2
homepage: https://docs.yaroo.dev/orm/quickstart
repository: https://github.com/codekeyz/yaroo

topics:
  - yaroo
  - postgres
  - mariadb
  - mysql
  - sqlite

environment:
  sdk: ^3.0.0

dependencies:
  sqflite_common_ffi:
  sqflite_common: ^2.5.3
  mysql_client: ^0.0.27
  postgres: ^3.1.1

  meta: ^1.11.0
  collection: ^1.18.0
  grammer: ^1.0.3
  recase: ^4.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  yaroo_cli:
    path: ../yaroo_cli
  path: ^1.9.0
